'use client';
import { useEffect, useState, type FormEvent } from 'react';
import type { Block, Reservation, ReservationStatus } from '../../lib/types';

export default function Admin(){
 const [secret,setSecret]=useState(''); const [ok,setOk]=useState(false); const [rows,setRows]=useState<Reservation[]>([]); const [blocks,setBlocks]=useState<Block[]>([]); const [msg,setMsg]=useState(''); const [loading,setLoading]=useState(false); const [blockForm,setBlockForm]=useState({start:'',end:'',reason:''});
 async function load(){const r=await fetch('/api/admin',{cache:'no-store'});const d=await r.json();if(r.ok&&d.ok){setRows(d.reservations||[]);setBlocks(d.blocks||[]);setOk(true)}else if(r.status===401)setOk(false);else setMsg(d.error||'Error')}
 async function login(e:FormEvent){e.preventDefault();setLoading(true);const r=await fetch('/api/admin',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'login',secret})});const d=await r.json();setLoading(false);if(!r.ok){setMsg(d.error||'Clave incorrecta');return}setMsg('');load()}
 useEffect(()=>{load()},[]);
 async function action(body:unknown){setMsg('');const r=await fetch('/api/admin',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json();if(!r.ok||!d.ok){setMsg(d.error||'No autorizado');return}setMsg('Actualizado correctamente');load()}
 if(!ok)return <main className="admin-login"><form className="admin-card" onSubmit={login}><span className="eyebrow">LOS ABUELOS · CHACRA</span><h1>Panel administrativo</h1><p>Acceso privado para gestionar reservas y fechas.</p><input autoFocus type="password" placeholder="Clave de administración" value={secret} onChange={e=>setSecret(e.target.value)}/><button className="primary" disabled={loading}>{loading?'Ingresando…':'INGRESAR'}</button>{msg&&<div className="message">{msg}</div>}<small>La clave se valida exclusivamente en el servidor.</small></form></main>;
 return <main className="admin"><div className="admin-top"><div><span className="eyebrow">LOS ABUELOS · CHACRA</span><h1>Reservas</h1></div><button onClick={load}>Actualizar</button></div>{msg&&<div className="message">{msg}</div>}<section className="admin-section"><h2>Bloquear fechas</h2><div className="block-form"><input type="date" value={blockForm.start} onChange={e=>setBlockForm({...blockForm,start:e.target.value})}/><input type="date" value={blockForm.end} onChange={e=>setBlockForm({...blockForm,end:e.target.value})}/><input placeholder="Motivo (opcional)" value={blockForm.reason} onChange={e=>setBlockForm({...blockForm,reason:e.target.value})}/><button onClick={()=>{if(!blockForm.start||!blockForm.end||blockForm.end<=blockForm.start)return setMsg('Elegí un rango válido.');action({op:'block',...blockForm});setBlockForm({start:'',end:'',reason:''})}}>BLOQUEAR FECHAS</button></div>{blocks.length>0&&<div className="block-list">{blocks.map(b=><div key={b.id}><span>{b.start} → {b.end}</span><small>{b.reason||'Sin motivo'}</small><button onClick={()=>action({op:'unblock',id:b.id})}>Liberar</button></div>)}</div>}</section><div className="table-wrap"><table><thead><tr><th>Fecha creación</th><th>Fechas</th><th>Huésped</th><th>Contacto</th><th>Personas</th><th>Tipo</th><th>Total</th><th>Seña</th><th>Estado</th><th>Observaciones</th><th>Acciones</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td>{new Date(r.createdAt).toLocaleString('es-AR')}</td><td>{r.start}<br/>→ {r.end}</td><td>{r.name}</td><td>{r.phone}<br/>{r.email}</td><td>{r.people||'Masivo'}</td><td>{r.type}</td><td>${Number(r.total).toLocaleString('es-AR')}</td><td>${Number(r.deposit).toLocaleString('es-AR')}</td><td><span className={`status ${r.status.toLowerCase()}`}>{r.status}</span></td><td>{r.notes||'—'}</td><td><div className="actions">{r.status==='PENDIENTE'&&<button onClick={()=>action({op:'status',id:r.id,status:'CONFIRMADA' as ReservationStatus})}>Confirmar</button>}{(r.status==='PENDIENTE'||r.status==='CONFIRMADA')&&<><button onClick={()=>action({op:'status',id:r.id,status:'LIBERADA' as ReservationStatus})}>Liberar</button>{r.status==='CONFIRMADA'&&<button onClick={()=>action({op:'status',id:r.id,status:'CANCELADA' as ReservationStatus})}>Cancelar</button>}</>}</div></td></tr>)}</tbody></table></div></main>
}
